<Project>
  <ItemGroup Condition="'$(MSBuildProjectName)' != 'Game.Analyzers'">
    <ProjectReference Include="$(MSBuildThisFileDirectory)Game.Analyzers\Game.Analyzers.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
