import argparse
import datetime
import json
import pathlib
import re
from typing import Any


def _load_json(path: pathlib.Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json(path: pathlib.Path, obj: Any) -> None:
    path.write_text(json.dumps(obj, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _write_text(path: pathlib.Path, text: str) -> None:
    path.write_text(text, encoding="utf-8")


def _ensure_list(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(x).strip() for x in value if str(x).strip()]
    if isinstance(value, str):
        v = value.strip()
        return [v] if v else []
    return [str(value).strip()]


def _find_view_task(gameplay: list[dict], back: list[dict], task_id: int) -> dict | None:
    for item in gameplay:
        raw = item.get("taskmaster_id")
        if str(raw).isdigit() and int(raw) == task_id:
            return item
    for item in back:
        raw = item.get("taskmaster_id")
        if str(raw).isdigit() and int(raw) == task_id:
            return item
    return None


def _read_file_safe(path: pathlib.Path) -> str | None:
    if not path.exists() or not path.is_file():
        return None
    return path.read_text(encoding="utf-8")


def _scan_acc_markers(text: str, task_id: int) -> set[int]:
    # ACC:T<id>.<n>
    pattern = re.compile(rf"ACC:T{task_id}\.(\d+)")
    return {int(m.group(1)) for m in pattern.finditer(text)}


def _render_md(report: dict) -> str:
    lines: list[str] = []
    lines.append(f"# Subtasks Coverage Audit (T{report['range']['start']}..T{report['range']['end']})\n\n")
    lines.append("Generated by `scripts/python/llm_check_subtasks_coverage.py`.\n\n")
    lines.append(f"- Date: {report['date']}\n")
    lines.append(f"- Tasks analyzed: {report['summary']['tasks_analyzed']}\n")
    lines.append(f"- Tasks with no subtasks: {report['summary']['tasks_without_subtasks']}\n")
    lines.append(f"- Tasks with missing ACC markers: {report['summary']['tasks_with_missing_acc_markers']}\n\n")

    lines.append("## Findings\n\n")
    for item in report["tasks"]:
        tid = item["task_id"]
        title = item.get("title", "")
        lines.append(f"### T{tid} {title}\n\n")
        if item["subtasks_count"] == 0:
            lines.append("- Gap: No subtasks defined in master task.\n\n")
            continue

        if item["missing_subtask_ids"]:
            lines.append(f"- Missing ACC markers for subtasks: {item['missing_subtask_ids']}\n")
        else:
            lines.append("- ACC markers: OK (all subtasks covered)\n")

        if item["missing_test_refs"]:
            lines.append("- Gap: test_refs empty (cannot audit ACC markers)\n")

        missing_files = item.get("missing_test_ref_files") or []
        if missing_files:
            lines.append("- Missing test_ref files:\n")
            for f in missing_files:
                lines.append(f"  - {f}\n")

        lines.append("\n")
    return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--task-id-start", type=int, default=27)
    parser.add_argument("--task-id-end", type=int, default=43)
    args = parser.parse_args()

    root = pathlib.Path(__file__).resolve().parents[2]
    tasks_path = root / ".taskmaster" / "tasks" / "tasks.json"
    gameplay_path = root / ".taskmaster" / "tasks" / "tasks_gameplay.json"
    back_path = root / ".taskmaster" / "tasks" / "tasks_back.json"

    tasks_obj = _load_json(tasks_path)
    gameplay_obj = _load_json(gameplay_path)
    back_obj = _load_json(back_path)

    if not isinstance(gameplay_obj, list) or not isinstance(back_obj, list):
        raise TypeError("Expected tasks_gameplay.json and tasks_back.json to be top-level lists.")

    master_tasks = tasks_obj.get("master", {}).get("tasks", [])
    if not isinstance(master_tasks, list):
        raise TypeError("Expected tasks.json master.tasks to be a list.")
    master_by_id = {int(t["id"]): t for t in master_tasks if str(t.get("id", "")).isdigit()}

    tasks_report: list[dict] = []
    tasks_without_subtasks = 0
    tasks_with_missing_acc_markers = 0

    for task_id in range(args.task_id_start, args.task_id_end + 1):
        master = master_by_id.get(task_id)
        if not master:
            continue
        view = _find_view_task(gameplay_obj, back_obj, task_id)

        subtasks = master.get("subtasks")
        subtasks = subtasks if isinstance(subtasks, list) else []
        subtask_ids = [int(s.get("id")) for s in subtasks if str(s.get("id", "")).isdigit()]

        title = (master.get("title") or "").strip()

        test_refs = _ensure_list(view.get("test_refs") if view else None)
        missing_test_refs = len(test_refs) == 0
        missing_test_ref_files: list[str] = []

        seen_acc_ids: set[int] = set()
        for rel in test_refs:
            test_path = root / rel
            content = _read_file_safe(test_path)
            if content is None:
                missing_test_ref_files.append(rel)
                continue
            seen_acc_ids |= _scan_acc_markers(content, task_id)

        missing_subtask_ids = []
        if subtask_ids:
            missing_subtask_ids = sorted([sid for sid in subtask_ids if sid not in seen_acc_ids])

        if not subtasks:
            tasks_without_subtasks += 1
        elif missing_subtask_ids:
            tasks_with_missing_acc_markers += 1

        tasks_report.append(
            {
                "task_id": task_id,
                "title": title,
                "view_id": view.get("id") if view else None,
                "subtasks_count": len(subtasks),
                "subtask_ids": subtask_ids,
                "test_refs": test_refs,
                "missing_test_refs": missing_test_refs,
                "missing_test_ref_files": missing_test_ref_files,
                "seen_acc_ids": sorted(seen_acc_ids),
                "missing_subtask_ids": missing_subtask_ids,
            }
        )

    date = datetime.date.today().isoformat()
    out_dir = root / "logs" / "ci" / date / "task-mapping"
    out_dir.mkdir(parents=True, exist_ok=True)
    suffix = f"T{args.task_id_start:02d}-T{args.task_id_end:02d}"
    out_json = out_dir / f"subtasks-coverage--{suffix}.json"
    out_md = out_dir / f"subtasks-coverage--{suffix}.md"

    report = {
        "ts": datetime.datetime.utcnow().isoformat() + "Z",
        "date": date,
        "range": {"start": args.task_id_start, "end": args.task_id_end},
        "summary": {
            "tasks_analyzed": len(tasks_report),
            "tasks_without_subtasks": tasks_without_subtasks,
            "tasks_with_missing_acc_markers": tasks_with_missing_acc_markers,
        },
        "tasks": tasks_report,
        "notes": [
            "This audit treats master.subtasks as the semantic 'must-do' breakdown when present.",
            "Coverage is checked via ACC markers in files referenced by view.test_refs (ACC:T<id>.<n>).",
            "If a task defines subtasks but test_refs is empty, coverage cannot be audited deterministically.",
        ],
    }

    _write_json(out_json, report)
    _write_text(out_md, _render_md(report))

    print(f"Wrote {out_json}")
    print(f"Wrote {out_md}")
    print(
        f"tasks_analyzed={report['summary']['tasks_analyzed']} "
        f"tasks_without_subtasks={tasks_without_subtasks} "
        f"tasks_with_missing_acc_markers={tasks_with_missing_acc_markers}"
    )

    # Non-blocking: this is an audit tool.
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
